//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopDAL
{
    using System;

    public partial class Comment
    {
        public int CommentId { get; set; }
        public Guid AnimalId { get; set; }
        public string Comment1 { get; set; }

        public Animal Animal { get; set; }
    }
}
